version: "3"
services:
  scimongo:
    container_name: scimongo
    image: mongo:4.2
    ports:
    - "27017:27017"

   
  
  # frontend:
  #   image:  dacat/catanie:latest
  #   container_name: frontend
  #   # build:
  #   #   context: ./frontend
  #   #   dockerfile: Dockerfile.dev
  #   volumes:
  #   - ./frontend:/frontend
  #   - ./scicat-als-config/frontend/dev-config.json:/usr/share/nginx/html/assets/config.json
  #   - ./scicat-als-config/frontend/alslogo.png:/usr/share/nginx/html/assets/images/site-logo.png
  #   # environment: 
  #   # - env=als-dev
  #   ports:
  #   - '80:80'
  #   # - '80:4200'
  #   # command: sleep 9999999

  backend:
     build:
       context: ./scicat-backend-next
     ports:
       - '3000:3000'
     depends_on:
       - scimongo
       # - openldap
     environment:
       MONGODB_URI: mongodb://scimongo:27017/scicat
       EXPRESS_SESSION_SECRET: "${EXPRESS_SESSION_SECRET}"
       JWT_SECRET: "${JWT_SECRET}"
       PORT: 3000
       HTTP_MAX_REDIRECTS: 5
       HTTP_TIMEOUT: 5000
       JWT_EXPIRES_IN: 3600
       SITE: SAMPLE-SITE
       PID_PREFIX: PID.SAMPLE.PREFIX
       DOI_PREFIX: DOI.SAMPLE.PREFIX
       METADATA_KEYS_RETURN_LIMIT: 100
       METADATA_PARENT_INSTANCES_RETURN_LIMIT: 100
       ADMIN_GROUPS: admin, ingestor

    
