version: "3"
services:
  scimongo:
    container_name: scimongo
    image: mongo:4.2
    ports:
    - "127.0.0.1:27017:27017"
  
  # frontend:
  #   image:  dacat/catanie:latest
  #   container_name: frontend
  #   # build:
  #   #   context: ./frontend
  #   #   dockerfile: Dockerfile.dev
  #   volumes:
  #   - ./frontend:/frontend
  #   - ./scicat-als-config/frontend/dev-config.json:/usr/share/nginx/html/assets/config.json
  #   - ./scicat-als-config/frontend/alslogo.png:/usr/share/nginx/html/assets/images/site-logo.png
  #   # environment: 
  #   # - env=als-dev
  #   ports:
  #   - '80:80'
  #   # - '80:4200'
  #   # command: sleep 9999999

  # backend:
  #   build:
  #     context: ./scicat-backend-next
    
